configured_endpoints: 86
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/undefined-selalipop%2Freddit-ad-api-732bac2b012cbe2d164410badf420bd05cf6581292c5cf8a2667cd8cac2f16fd.yml
openapi_spec_hash: e78ca8cd82dbf0163ef6fbbc54c19324
config_hash: eaeca11f57f4b3f5219bbb5bf3f33a5e
